service: web-proxy-bot
frameworkVersion: "3"

provider:
  name: yandex-cloud
  runtime: nodejs16
  httpApi:
    payload: "1.0"

plugins:
  - "@yandex-cloud/serverless-plugin"

package:
  patterns:
    - "!**"
    - .env
    - package.json
    # - package-lock.json
    - dist/*.js

functions:
  main:
    handler: dist/index.handler
    memorySize: 128
    timeout: "5"
    account: function-sa
    events:
      - http:
          path: /webhook
          method: post

  # timer:
  #   handler: dist/index.hello
  #   memorySize: 128
  #   timeout: '5'
  #   events:
  #     - cron:
  #         expression: "* * * * ? *"
  #         account: trigger-sa
  #         retry:
  #           attempts: 1
  #           interval: 10

resources:
  # trigger-sa:
  #   type: yc::ServiceAccount
  #   roles:
  #     - serverless.functions.invoker
  function-sa:
    type: yc::ServiceAccount
    roles:
      - editor
